export const FIELD_HELP: Record<string, string> = {
  "agents.defaults.workspace": "Workspace directory for agent context files and memory.",
  "agents.defaults.provider": "Preferred provider name (e.g. anthropic, openai, gemini). Leave empty to auto-select the first configured provider.",
  "agents.defaults.maxTokens": "Maximum tokens per response.",
  "agents.defaults.temperature": "Sampling temperature for model responses.",
  "agents.defaults.maxToolIterations": "Maximum tool calls per turn.",
  "agents.context.bootstrap.files": "Files injected into the system prompt at startup.",
  "agents.context.bootstrap.minimalFiles": "Minimal file set used for low-context runs.",
  "agents.context.bootstrap.heartbeatFiles": "Files checked periodically for tasks.",
  "agents.context.bootstrap.perFileChars": "Max chars per bootstrap file.",
  "agents.context.bootstrap.totalChars": "Max total chars across bootstrap files.",
  "agents.context.memory.enabled": "Enable memory injection from memory files.",
  "agents.context.memory.maxChars": "Max characters of memory injected per turn.",
  "providers.*": "Configure credentials and endpoints for this provider.",
  "providers.openai": "Leading AI models including GPT-4 and GPT-3.5.",
  "providers.*.apiKey": "API key for this provider.",
  "providers.*.apiBase": "Override the provider API base URL if needed.",
  "providers.*.model": "Model to use for regular agent requests (e.g. claude-opus-4-6, gpt-4o).",
  "providers.*.utilityModel": "Optional lighter model for compaction and memory extraction. Falls back to model if not set.",
  "providers.*.extraHeaders": "Extra headers to send to the provider.",
  "providers.*.wireApi": "Select API mode (auto/chat/responses) for providers that support it.",
  "tools.web.search.apiKey": "API key for the configured web search provider.",
  "tools.web.search.maxResults": "Default number of search results.",
  "tools.exec.timeout": "Command execution timeout (seconds).",
  "tools.restrictFilesToWorkspace": "Restrict file read/write/edit/list tools to the workspace directory.",
  "tools.restrictExecToWorkspace": "Restrict exec path arguments to the workspace directory. Disable to allow running system binaries like node or npm.",
  "channels.*": "Configure connection and credentials for this channel.",
  "channels.telegram": "Connect with Telegram bots for instant messaging.",
  "channels.slack": "Integrate with Slack workspaces for team collaboration.",
  "channels.webhook": "Receive HTTP webhooks for custom integrations.",
  "channels.whatsapp.bridgeUrl": "WebSocket URL for the WhatsApp bridge.",
  "channels.whatsapp.allowFrom": "Phone numbers allowed to message the agent (international format without +, e.g. 14155552671). Leave empty + set policy=none to allow all.",
  "channels.whatsapp.policy": "restricted = only allowFrom list; none = allow everyone.",
  "channels.telegram.token": "Telegram bot token.",
  "channels.telegram.proxy": "Optional HTTP proxy for Telegram.",
  "channels.telegram.allowfrom": "Only messages from this user are allowed.",
  "channels.slack.mode": "Slack connection mode (socket or webhook).",
  "channels.slack.webhookPath": "Slack webhook path when using webhook mode.",
  "channels.slack.botToken": "Slack bot token.",
  "channels.slack.appToken": "Slack app-level token.",
  "channels.slack.groupPolicy": "Group policy for Slack channels.",
  "channels.slack.dm.policy": "DM policy for Slack.",
  "tools.caldav.enabled": "Enable CalDAV calendar tools (list, read, create, update, delete events).",
  "tools.caldav.serverUrl": "CalDAV server URL (e.g. https://nextcloud.example.com/remote.php/dav).",
  "tools.caldav.username": "CalDAV username.",
  "tools.caldav.password": "CalDAV password or app-specific password. Store securely in the vault instead: verox vault set config.tools.caldav.password <value>",
  "tools.caldav.defaultCalendar": "Default calendar name for create operations (partial match). Uses first calendar if blank.",
  "tools.browser.enabled": "Enable Playwright browser automation tools (requires 'npx playwright install chromium').",
  "tools.browser.headless": "Run browser in headless mode (no visible window). Default: true.",
  "tools.browser.timeout": "Default element/navigation timeout in milliseconds. Default: 30000.",
  "tools.browser.allowedDomains": "Restrict browser to these hostnames only. Empty = allow all.",
  "mcp.servers": "Map of MCP server names to their connection config.",
  "mcp.servers.*.transport": "Transport type: stdio (local process) or sse / http (remote server).",
  "mcp.servers.*.command": "Executable to launch for stdio transport (e.g. npx, uvx).",
  "mcp.servers.*.args": "Arguments passed to the stdio command.",
  "mcp.servers.*.env": "Extra environment variables for the stdio process. Use 'vault:<key>' for a full-value secret (variable omitted if missing), or '$vault:<key>' to embed a secret inside a larger value — e.g. API_KEY=vault:config.mcp.servers.myserver.apikey",
  "mcp.servers.*.url": "URL for sse or http transport (e.g. http://localhost:3001/sse).",
  "mcp.servers.*.headers": "HTTP headers for sse/http transports. Use 'vault:<key>' for a full-value secret, or '$vault:<key>' to embed within a value — e.g. Authorization=Bearer $vault:config.mcp.servers.myserver.token",
  "mcp.servers.*.alwaysInclude": "When true, this server's tools are always sent to the LLM regardless of the user message. When false (default), tools are only included when the message contains keywords matching their name or description — keeping the prompt short for unrelated requests.",
};