export const FIELD_LABELS: Record<string, string> = {
  agents: "Agents",
  "agents.defaults": "Agent Defaults",
  "agents.defaults.workspace": "Workspace",
  "agents.defaults.provider": "Default Provider",
  "agents.defaults.maxTokens": "Max Tokens",
  "agents.defaults.temperature": "Temperature",
  "agents.defaults.maxToolIterations": "Max Tool Iterations",
  "agents.context": "Context",
  "agents.context.bootstrap": "Bootstrap Files",
  "agents.context.bootstrap.files": "Bootstrap Files",
  "agents.context.bootstrap.minimalFiles": "Minimal Files",
  "agents.context.bootstrap.heartbeatFiles": "Heartbeat Files",
  "agents.context.bootstrap.perFileChars": "Max Chars per File",
  "agents.context.bootstrap.totalChars": "Total Bootstrap Chars",
  "agents.context.memory": "Memory",
  "agents.context.memory.enabled": "Enable Memory",
  "agents.context.memory.maxChars": "Max Memory Chars",
  providers: "Providers",
  "providers.*.apiKey": "API Key",
  "providers.*.apiBase": "API Base URL",
  "providers.*.model": "Model",
  "providers.*.utilityModel": "Utility Model",
  "providers.*.extraHeaders": "Extra Headers",
  "providers.*.wireApi": "Wire API Mode",
  "providers.*.promptCaching": "Prompt Caching",
  channels: "Channels",
  gateway: "Gateway",
  "gateway.host": "Gateway Host",
  "gateway.port": "Gateway Port",
  ui: "UI",
  "ui.enabled": "Enable UI",
  "ui.host": "UI Host",
  "ui.port": "UI Port",
  "ui.open": "Open Browser",
  tools: "Tools",
  "tools.web": "Web Tools",
  "tools.web.search": "Web Search",
  "tools.web.search.apiKey": "Search API Key",
  "tools.web.search.maxResults": "Max Results",
  "tools.exec": "Command Execution",
  "tools.exec.timeout": "Exec Timeout (seconds)",
  "tools.smtp": "SMTP (Email Send)",
  "tools.smtp.enabled": "Enable SMTP",
  "tools.smtp.host": "SMTP Host",
  "tools.smtp.port": "SMTP Port",
  "tools.smtp.secure": "Use TLS (port 465)",
  "tools.smtp.user": "Username",
  "tools.smtp.password": "Password",
  "tools.smtp.from": "From Address",
  "tools.smtp.replyTo": "Reply-To Address",
  "tools.smtp.defaultCC": "Default CC",
  "tools.smtp.signature": "Email Signature",
  "tools.restrictFilesToWorkspace": "Restrict File Access to Workspace",
  "tools.restrictExecToWorkspace": "Restrict Exec Paths to Workspace",
  "plugins": "Plugins",
  "plugins.enabled": "Enable Plugins",
  "plugins.allow": "Plugin Allowlist",
  "plugins.deny": "Plugin Denylist",
  "plugins.load": "Plugin Load Paths",
  "plugins.load.paths": "Plugin Paths",
  "plugins.entries": "Plugin Entries",
  "plugins.entries.*.enabled": "Plugin Enabled",
  "plugins.entries.*.config": "Plugin Config",
  "plugins.installs": "Plugin Installs",
  "plugins.installs.*.source": "Install Source",
  "plugins.installs.*.spec": "NPM Spec",
  "plugins.installs.*.sourcePath": "Source Path",
  "plugins.installs.*.installPath": "Install Path",
  "plugins.installs.*.version": "Installed Version",
  "plugins.installs.*.installedAt": "Installed At",
  "channels.whatsapp": "WhatsApp",
  "channels.whatsapp.enabled": "Enabled",
  "channels.whatsapp.bridgeUrl": "Bridge URL",
  "channels.whatsapp.allowFrom": "Allow From",
  "channels.telegram": "Telegram",
  "channels.telegram.enabled": "Enabled",
  "channels.telegram.token": "Bot Token",
  "channels.telegram.allowFrom": "Allow From",
  "channels.telegram.proxy": "Proxy",
  "channels.slack": "Slack",
  "channels.slack.enabled": "Enabled",
  "channels.slack.mode": "Mode",
  "channels.slack.webhookPath": "Webhook Path",
  "channels.slack.botToken": "Bot Token",
  "channels.slack.appToken": "App Token",
  "channels.slack.userTokenReadOnly": "User Token Read Only",
  "channels.slack.groupPolicy": "Group Policy",
  "channels.slack.groupAllowFrom": "Group Allow From",
  "channels.slack.dm": "DM",
  "channels.slack.dm.enabled": "Enabled",
  "channels.slack.dm.policy": "DM Policy",
  "channels.slack.dm.allowFrom": "Allow From"
};